version: '2'
services:
    invoister-app:
        image: invoister
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://invoister-mysql:3306/invoister?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://invoister-elasticsearch:9200
        ports:
            - 8080:8080
    invoister-mysql:
        extends:
            file: mysql.yml
            service: invoister-mysql
    invoister-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: invoister-elasticsearch
